// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbhxP-fSQwsbO2dqz0aTvwS7gso4iQtO8',
    appId: '1:516897022321:web:966b310e091251361316d0',
    messagingSenderId: '516897022321',
    projectId: 'mchn-text',
    authDomain: 'mchn-text.firebaseapp.com',
    storageBucket: 'mchn-text.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCY6YKs9gnG6_20-XtfEHuoLp0IBgrwPSo',
    appId: '1:516897022321:android:d72a63ed701b9be21316d0',
    messagingSenderId: '516897022321',
    projectId: 'mchn-text',
    storageBucket: 'mchn-text.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe9mRBIHCF6uOKB11TLHkpI1yXls7KNMA',
    appId: '1:516897022321:ios:a99829a89a6916071316d0',
    messagingSenderId: '516897022321',
    projectId: 'mchn-text',
    storageBucket: 'mchn-text.firebasestorage.app',
    iosBundleId: 'com.example.mechineText',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe9mRBIHCF6uOKB11TLHkpI1yXls7KNMA',
    appId: '1:516897022321:ios:a99829a89a6916071316d0',
    messagingSenderId: '516897022321',
    projectId: 'mchn-text',
    storageBucket: 'mchn-text.firebasestorage.app',
    iosBundleId: 'com.example.mechineText',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbhxP-fSQwsbO2dqz0aTvwS7gso4iQtO8',
    appId: '1:516897022321:web:714aec77c42fc58c1316d0',
    messagingSenderId: '516897022321',
    projectId: 'mchn-text',
    authDomain: 'mchn-text.firebaseapp.com',
    storageBucket: 'mchn-text.firebasestorage.app',
  );
}
